spring:
  application:
    name: proyecto_integrador_cesde_2026

  datasource:
    url: jdbc:mysql://localhost:3306/proyecto_integrador_cesde_2026?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: santiago
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true